### PR TITLE
Change btree.c to compile with all versions of LMDB

### PR DESCRIPTION
**Pull request by maxwell-k**
After applying this PR LMDB will compile against all the current versions of LMDB. Versions above 
0.9.16 fail as noted in #7 

- [x] Try to separate out copyright changes
- [ ] Benchmarking version 2
    - [ ] Outline process to go from source code to gh-pages
    - [ ] Process should keep version 1 as an artefact    
    - [ ] Change the versions of SQLite shown in the table
- [ ] Ideas for version 2:
    - [ ] Include raw HTML files as produced by TCL script in gh-pages

Potentially has a negative effect on performance, **do not merge until the performance impact has been assessed** by sharing bench marking data

### CODE REVIEW

**Comment by maxwell-k** [comment]
Dan commented on the other PR, before I closed it by mistake that he's pretty sure there isn't a performance impact. 

I intend to measure the performance impact of this PR before merging.

**Comment by maxwell-k** [comment]
This can be taken forward with a second version of the benchmarking after https://github.com/LumoSQL/LumoSQL/pull/20 .

Split out the copyright changes into a separate PR.

**Comment by maxwell-k** [comment]
At the moment I'm going to suggest showing the following in benchmarking version 2

A. sqlite.org 3.30.1 as in version 1
B. sqlite.org 3.31.1 which is from 2020
C. 3.7.17 with LMDB 0.9.16 before applying this patch as in version 1
D. 3.7.17 with LMDB 0.9.16 after applying this patch

**Review by danshearer — APPROVED** [review]
Approved, as discussed

**Pull request merged**
